# 这个应用的访问地址
base_url: http://weixin.qnnsafe.com

# 关注后显示的内容
newly_subscribed: |
  您好！欢迎加入全能保险柜微信平台这个大家庭！
  需要了解什么呢？让我来帮您解答吧！
  您可在菜单栏快速点选功能，也可以直接输入数字指令！
  回复“0”获得更多帮助
  <a href="http://www.qnnsafe.com">点击进入全能官网</a> 

  全能保险柜，保险柜行业的全能冠军！
  缔造全能安全生活空间！ 
  全国客服热线：400-830-4555。

# 机器人自动回复
# 检查类型：regex, exact
# 测试内容：tests
# 回复类型：words, sound
robots:
  - regex: ["^(gnu|linux|gnu[\\/+\\-\\s&.,:]?linux)$", "i"]
    tests: ['GNU','LiNux','GnU/LiNuX']
    sound: ['/sounds/gnulinux.mp3', '/sounds/gnulinux.mp3', 'What Is GNU/Linux?', 'Richard Stallman']
  - exact: help
    words: |
      This is an open source app. For more info, visit
      <a href="https://github.com/qnn/qnn-weixin">the repo on GitHub</a>.

# 最近店铺列表第一个大项的文字
title_of_first_nearby_store: 打开地图查看各销售网点位置

# 最近店铺每个项目右边的图像地址，最佳分辨率是80x80
default_nearby_store_image_url: http://www.qnnsafe.com/assets/images/qnn-icon-152.png

# 最近店铺显示个数
number_of_nearby_stores_to_list: 3

# ---------------------------------------------------------
# 用于测试的数据，如无必要，请勿更改
# test.coord              用于测试的坐标
# test.nearby_store_name  离坐标最近的店铺名
test:
  coord:
    lat: 22.849068
    lng: 113.216673
  nearby_store_name: 佛山大良专卖店
