# 这个应用的访问地址
base_url: http://weixin.qnnsafe.com

# 关注后显示的内容
newly_subscribed: |
  您好！欢迎加入全能保险柜微信平台这个大家庭！
  需要了解什么呢？让我来帮您解答吧！
  您可在菜单栏快速点选功能，也可以直接输入数字指令！
  回复“0”获得更多帮助
  <a href="http://www.qnnsafe.com">点击进入全能官网</a> 

  全能保险柜，保险柜行业的全能冠军！
  缔造全能安全生活空间！ 
  全国客服热线：400-830-4555。

# 机器人自动回复
# 检查类型：regex, exact
# 测试内容：tests
# 回复类型：words, sound
robots:
  - regex: ["^(gnu|linux|gnu[\\/+\\-\\s&.,:]?linux)$", "i"]
    tests: ['GNU','LiNux','GnU/LiNuX']
    sound: ['/sounds/gnulinux.mp3', '/sounds/gnulinux.mp3', 'What Is GNU/Linux?', 'Richard Stallman']

  - exact: help
    words: |
      This is an open source app. For more info, visit
      <a href="https://github.com/qnn/qnn-weixin">the repo on GitHub</a>.

  - click: MENU_PRODUCTS
    lists: LIST_PRODUCTS

  - click: ['MENU_BUYERS_GUIDE', 'MENU_CLEAN']
    words: 抱歉，资料添加中，请稍后查阅...

  - click: MENU_FIND_STORE
    words: |
      点击屏幕左下方功能键“+”，在展开的菜单中点选“位置”，发送你的坐标位置就可查找到离你最近的全能销售网点。
      
      如果你无法获取坐标，也可以前往<a href="http://www.qnnsafe.com/network/">手机版官网</a>查询。

menus:
  全能之家:
    全能官网: http://www.qnnsafe.com/
    招商加盟: http://www.qnnsafe.com.cn/
    全能产品: MENU_PRODUCTS
  自助服务:
    导购精灵: MENU_BUYERS_GUIDE
    网点查询: MENU_FIND_STORE
    天猫旗舰: http://qnn.tmall.com/
    常见问题: MENU_FAQ
    清洁保养: MENU_CLEAN
  活动专区:
    全能资讯: http://www.qnnsafe.com/news/


lists:
  LIST_PRODUCTS:
    link_base_url: http://www.qnnsafe.com
    image_base_url: http://www.qnnsafe.com/images/weixin/
    items:
      - words: 梦想全能实现
        links: /
        image: quanjiafu.jpg

      - words: 【全能风生水起】 中国首款风水保险柜
        links: /bw-6960.html
        image: bw.jpg

      - words: 【全能指点江山】 指点江山，运筹帷幄
        links: /zf-4542.html
        image: zf.jpg

      - words: 【全能钢将军】 实用为王，储物自如
        links: /fg-2940br.html
        image: fg.jpg

      - words: 【全能金库】 防盗技术，全球领先
        links: /b-4538.html
        image: b.jpg

      - words: 【全能新皇冠】 安全典范，生活品味
        links: /hg-2740.html
        image: hg.jpg

      - words: 【全能铁管家】 3C认证，品质保证
        links: /sjb-1630br.html
        image: sjb.jpg

      - words: 【全能文件柜】 精明老板，明智之选
        links: /bmg-7545ab.html
        image: bmg.jpg

      - words: 【全能高尔夫】 精英格调，赏心悦目
        links: /glf-3340.html
        image: glf.jpg

      - words: 【全能铁金刚】 睿智沉稳，精英气息
        links: /tgg-2040br.html
        image: tgg.jpg

      - words: 【全能钢铁侠】 装甲精良，豪侠气概
        links: /gtx-3345.html
        image: bw.jpg

      - words: 【全能可拉】 时尚安全，和谐统一
        links: /kl-4045.html
        image: kl.jpg


# 图文列表过长时最后一项显示的文字
list_item_last: 查看全部...

# 最近店铺列表第一个大项的文字
title_of_first_nearby_store: 打开地图查看各销售网点位置

# 最近店铺每个项目右边的图像地址，最佳分辨率是80x80
default_nearby_store_image_url: http://www.qnnsafe.com/assets/images/qnn-icon-152.png

# 最近店铺显示个数
number_of_nearby_stores_to_list: 3

# ---------------------------------------------------------
# 用于测试的数据，如无必要，请勿更改
# test.coord              用于测试的坐标
# test.nearby_store_name  离坐标最近的店铺名
test:
  coord:
    lat: 22.849068
    lng: 113.216673
  nearby_store_name: 佛山大良专卖店
